title: Ran Wang # your name (or website title) here
logo: "/images/PICTURE.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's in City Planning Student, University of Pennsylvania. Received Bachelor of Arts from New York University in Sociology and Metropolitan Studies. 
  <br><br>
  Currently interning at EconsultSolutions as research assisstant on Freddie Mac project for housing affordability and zoning restrictiveness.
  <br><br>
  <a href="https://www.linkedin.com/in/ran-wang-4a70611ab/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
